/** Generated by scripts/gen-od-design-systems.mjs — do not edit manually. */
export interface DesignSystemCatalogEntry {
  id: string;
  label: string;
  labelZh?: string;
  category: string;
  summary: string;
  summaryZh?: string;
  swatches?: string[];
  isDefault?: boolean;
}

export const DESIGN_SYSTEM_CATALOG: DesignSystemCatalogEntry[] = [
  {
    "id": "default",
    "label": "Neutral Modern",
    "labelZh": "中性现代",
    "category": "Starter",
    "summary": "A clean, product-oriented default. Use when the brief doesn't call for a specific mood — good for B2B tools, dashboards, and utility pages.",
    "summaryZh": "简洁的产品导向默认风格。适用于没有特定情绪要求的场景——适合 B2B 工具、仪表板和实用页面。",
    "swatches": [
      "#fafafa",
      "#ffffff",
      "#111111",
      "#6b6b6b"
    ],
    "isDefault": true
  },
  {
    "id": "agentic",
    "label": "Agentic",
    "labelZh": "Agentic",
    "category": "Themed & Unique",
    "summary": "Conversational AI-first interface with minimal controls, clear outcomes, and delegated task flows for agentic workflows.",
    "summaryZh": "对话式 AI 优先界面，控件简洁、结果清晰，支持代理工作流的委派任务流程。",
    "swatches": [
      "#0b1020",
      "#131b2f",
      "#f8fafc",
      "#8ea0b8"
    ],
    "isDefault": false
  },
  {
    "id": "airbnb",
    "label": "Airbnb",
    "labelZh": "Airbnb",
    "category": "E-Commerce & Retail",
    "summary": "Travel marketplace. Warm coral accent, photography-driven, rounded UI.",
    "summaryZh": "旅行市场平台。温暖珊瑚色调，摄影驱动，圆角 UI。",
    "swatches": [
      "#ffffff",
      "#222222",
      "#6a6a6a",
      "#dddddd"
    ],
    "isDefault": false
  },
  {
    "id": "airtable",
    "label": "Airtable",
    "labelZh": "Airtable",
    "category": "Design & Creative",
    "summary": "Spreadsheet-database hybrid. Colorful, friendly, structured data aesthetic.",
    "summaryZh": "电子表格与数据库的混合体。色彩丰富、友好易用的结构化数据美学。",
    "swatches": [
      "#ffffff",
      "#181d26",
      "#e0e2e6",
      "#1b61c9"
    ],
    "isDefault": false
  },
  {
    "id": "ant",
    "label": "Ant",
    "labelZh": "Ant",
    "category": "Professional & Corporate",
    "summary": "Structured, enterprise-focused design system emphasizing clarity, consistency, and efficiency for data-dense web applications.",
    "summaryZh": "结构化的企业级设计系统，强调清晰度、一致性和效率，专为数据密集型 Web 应用而设计。",
    "swatches": [
      "#ffffff",
      "#f7f8fa",
      "#1f1f1f",
      "#697386"
    ],
    "isDefault": false
  },
  {
    "id": "apple",
    "label": "Apple",
    "labelZh": "Apple",
    "category": "Media & Consumer",
    "summary": "Consumer electronics. Premium white space, SF Pro, cinematic imagery.",
    "summaryZh": "消费电子产品。简约留白设计，SF Pro 字体，电影级图像。",
    "swatches": [
      "#ffffff",
      "#f5f5f7",
      "#1d1d1f",
      "#6e6e73"
    ],
    "isDefault": false
  },
  {
    "id": "application",
    "label": "Application",
    "labelZh": "应用程序",
    "category": "Professional & Corporate",
    "summary": "App dashboard with purple-themed aesthetic, top-bar navigation, card-based layouts, and developer-first workflows.",
    "summaryZh": "紫色主题的应用仪表板，包含顶栏导航、卡片式布局和开发者优先的工作流程。",
    "swatches": [
      "#f6f7f9",
      "#ffffff",
      "#172033",
      "#6b7689"
    ],
    "isDefault": false
  },
  {
    "id": "arc",
    "label": "Arc Browser",
    "labelZh": "Arc Browser",
    "category": "Productivity & SaaS",
    "summary": "\"The browser that browses for you.\" Translucent surfaces, gradient warmth, sidebar-first layout.",
    "summaryZh": "为你而浏览的浏览器。半透明表面、渐变暖色调、侧边栏优先布局。",
    "swatches": [
      "#fdf3ec",
      "#ffffff",
      "#1a1a1f",
      "#8c8c93"
    ],
    "isDefault": false
  },
  {
    "id": "artistic",
    "label": "Artistic",
    "labelZh": "艺术风格",
    "category": "Creative & Artistic",
    "summary": "High-contrast, expressive style with creative typography and bold color choices for visually striking interfaces.",
    "summaryZh": "高对比度、富有表现力的设计风格，采用创意排版和大胆的色彩选择，打造视觉冲击力强的界面。",
    "swatches": [
      "#fbf6ee",
      "#fffdf8",
      "#201914",
      "#7a6d63"
    ],
    "isDefault": false
  },
  {
    "id": "atelier-zero",
    "label": "Atelier Zero",
    "labelZh": "Atelier Zero",
    "category": "Editorial · Studio",
    "summary": "A magazine-grade, collage-driven visual system: warm paper canvas, surreal plaster-and-architecture imagery, oversized display type, hairline rules, Roman-numer",
    "summaryZh": "杂志级拼贴视觉系统：温暖纸质画布、超现实石膏与建筑意象、超大展示字体、细线装饰、罗马数字章节标记和精致编辑注释。",
    "swatches": [
      "#ffffff",
      "#f7f7f7",
      "#111111",
      "#707070"
    ],
    "isDefault": false
  },
  {
    "id": "bento",
    "label": "Bento",
    "labelZh": "Bento",
    "category": "Layout & Structure",
    "summary": "Modular grid layout with card-like blocks, clear hierarchy, soft spacing, and subtle visual contrast for organized, scannable interfaces.",
    "summaryZh": "模块化网格布局，包含卡片式区块、清晰的层级结构、柔和的间距和微妙的视觉对比，打造有序、易扫描的界面。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "binance",
    "label": "Binance.US",
    "labelZh": "Binance.US",
    "category": "Fintech & Crypto",
    "summary": "Crypto exchange. Bold yellow accent on monochrome, trading-floor urgency.",
    "summaryZh": "加密货币交易所。单色底上的醒目黄色强调，营造交易大厅的紧迫感。",
    "swatches": [
      "#ffffff",
      "#1e2026",
      "#848e9c",
      "#e6e8ea"
    ],
    "isDefault": false
  },
  {
    "id": "bmw",
    "label": "BMW",
    "labelZh": "BMW",
    "category": "Automotive",
    "summary": "Luxury automotive. Dark premium surfaces, precise German engineering aesthetic.",
    "summaryZh": "豪华汽车品牌。深色高级表面，精准的德国工程美学。",
    "swatches": [
      "#ffffff",
      "#f5f5f5",
      "#262626",
      "#757575"
    ],
    "isDefault": false
  },
  {
    "id": "bmw-m",
    "label": "BMW M",
    "labelZh": "BMW M",
    "category": "Automotive",
    "summary": "Motorsport performance sub-brand. Near-black cockpit surfaces, BMW M tricolor accents, sharp engineering geometry.",
    "summaryZh": "赛车运动性能子品牌。近黑色座舱表面，BMW M 三色装饰，锐利的工程几何设计。",
    "swatches": [
      "#f7f8fa",
      "#ffffff",
      "#111827",
      "#64748b"
    ],
    "isDefault": false
  },
  {
    "id": "bold",
    "label": "Bold",
    "labelZh": "粗体",
    "category": "Bold & Expressive",
    "summary": "Strong visual presence with heavyweight typography, high-contrast colors, and commanding layouts.",
    "summaryZh": "采用粗体字重、高对比度配色和强势布局，呈现强烈的视觉冲击力。",
    "swatches": [
      "#ffffff",
      "#f7f7f7",
      "#111111",
      "#707070"
    ],
    "isDefault": false
  },
  {
    "id": "brutalism",
    "label": "Brutalism",
    "labelZh": "野蛮主义",
    "category": "Bold & Expressive",
    "summary": "Raw, anti-design aesthetic inspired by concrete architecture with unadorned elements, jarring layouts, and functional minimalism.",
    "summaryZh": "受混凝土建筑启发的原始反设计美学，采用未经修饰的元素、突兀的布局和功能性极简主义。",
    "swatches": [
      "#f5f1e8",
      "#ffffff",
      "#000000",
      "#555555"
    ],
    "isDefault": false
  },
  {
    "id": "bugatti",
    "label": "Bugatti",
    "labelZh": "Bugatti",
    "category": "Automotive",
    "summary": "Hypercar brand. Cinema-black canvas, monochrome austerity, monumental display type.",
    "summaryZh": "超级跑车品牌。影院黑画布，单色简约风，宏伟展示字体。",
    "swatches": [
      "#07111f",
      "#101d2f",
      "#f7fbff",
      "#8fa1b7"
    ],
    "isDefault": false
  },
  {
    "id": "cafe",
    "label": "Cafe",
    "labelZh": "咖啡馆",
    "category": "Creative & Artistic",
    "summary": "Cozy cafe-inspired interface with warm tones, soft typography, and clean layouts for a relaxed browsing experience.",
    "summaryZh": "温馨的咖啡馆风格界面，采用温暖色调、柔和字体和简洁布局，营造轻松的浏览体验。",
    "swatches": [
      "#fbf6ee",
      "#fffdf8",
      "#201914",
      "#7a6d63"
    ],
    "isDefault": false
  },
  {
    "id": "cal",
    "label": "Cal.com",
    "labelZh": "Cal.com",
    "category": "Productivity & SaaS",
    "summary": "Open-source scheduling. Clean neutral UI, developer-oriented simplicity.",
    "summaryZh": "开源日程安排工具。简洁中性的 UI，面向开发者的简约设计。",
    "swatches": [
      "#ffffff",
      "#242424",
      "#898989",
      "#0099ff"
    ],
    "isDefault": false
  },
  {
    "id": "canva",
    "label": "Canva",
    "labelZh": "Canva",
    "category": "Design & Creative",
    "summary": "Visual creation platform. Vivid purple-blue gradient, generous spacing, friendly geometry.",
    "summaryZh": "视觉创作平台。鲜艳的紫蓝渐变，宽松的间距，友好的几何形状。",
    "swatches": [
      "#ffffff",
      "#f4f5f7",
      "#0e1318",
      "#5f6368"
    ],
    "isDefault": false
  },
  {
    "id": "cisco",
    "label": "Cisco",
    "category": "Backend & Data",
    "summary": "Enterprise infrastructure brand. Dark trust surfaces, Cisco Blue signal, technical clarity.",
    "swatches": [
      "#0f1720",
      "#1b2530",
      "#ffffff",
      "#9e9ea2"
    ],
    "isDefault": false
  },
  {
    "id": "claude",
    "label": "Claude (Anthropic)",
    "labelZh": "Claude (Anthropic)",
    "category": "AI & LLM",
    "summary": "Anthropic's AI assistant. Warm terracotta accent, clean editorial layout.",
    "summaryZh": "Anthropic 的 AI 助手。采用温暖的赤陶色调和简洁的编辑布局。",
    "swatches": [
      "#f5f4ed",
      "#faf9f5",
      "#141413",
      "#5e5d59"
    ],
    "isDefault": false
  },
  {
    "id": "clay",
    "label": "Clay",
    "labelZh": "Clay",
    "category": "Design & Creative",
    "summary": "Creative agency. Organic shapes, soft gradients, art-directed layout.",
    "summaryZh": "创意代理风格。有机形状、柔和渐变、艺术化布局。",
    "swatches": [
      "#f7eee6",
      "#fff8f1",
      "#2b211c",
      "#8a7a70"
    ],
    "isDefault": false
  },
  {
    "id": "claymorphism",
    "label": "Claymorphism",
    "labelZh": "黏土拟态",
    "category": "Morphism & Effects",
    "summary": "Soft, rounded 3D-like shapes mimicking malleable clay with playful, puffy elements and colorful surfaces.",
    "summaryZh": "柔和圆润的3D风格形状，模仿可塑黏土质感，带有俏皮蓬松的元素和多彩表面。",
    "swatches": [
      "#f7eee6",
      "#fff8f1",
      "#2b211c",
      "#8a7a70"
    ],
    "isDefault": false
  },
  {
    "id": "clean",
    "label": "Clean",
    "labelZh": "简洁",
    "category": "Modern & Minimal",
    "summary": "Simplicity-focused design with ample whitespace, legible typography, and a limited color palette to reduce visual clutter.",
    "summaryZh": "注重简约的设计，配以充足的留白、清晰易读的排版和有限的配色方案，减少视觉杂乱。",
    "swatches": [
      "#ffffff",
      "#f7f7f7",
      "#111111",
      "#707070"
    ],
    "isDefault": false
  },
  {
    "id": "clickhouse",
    "label": "ClickHouse",
    "labelZh": "ClickHouse",
    "category": "Backend & Data",
    "summary": "Fast analytics database. Yellow-accented, technical documentation style.",
    "summaryZh": "快速分析数据库。黄色强调，技术文档风格。",
    "swatches": [
      "#000000",
      "#141414",
      "#ffffff",
      "#a0a0a0"
    ],
    "isDefault": false
  },
  {
    "id": "cohere",
    "label": "Cohere",
    "labelZh": "Cohere",
    "category": "AI & LLM",
    "summary": "Enterprise AI platform. Vibrant gradients, data-rich dashboard aesthetic.",
    "summaryZh": "企业级 AI 平台。鲜艳渐变色，数据丰富的仪表板美学。",
    "swatches": [
      "#ffffff",
      "#fafafa",
      "#000000",
      "#93939f"
    ],
    "isDefault": false
  },
  {
    "id": "coinbase",
    "label": "Coinbase",
    "labelZh": "Coinbase",
    "category": "Fintech & Crypto",
    "summary": "Crypto exchange. Clean blue identity, trust-focused, institutional feel.",
    "summaryZh": "加密货币交易所。简洁的蓝色标识，注重信任，机构级风格。",
    "swatches": [
      "#ffffff",
      "#eef0f3",
      "#0a0b0d",
      "#5b616e"
    ],
    "isDefault": false
  },
  {
    "id": "colorful",
    "label": "Colorful",
    "labelZh": "缤纷多彩",
    "category": "Bold & Expressive",
    "summary": "Vibrant, high-contrast palettes and gradients for engaging, memorable, and modern user experiences.",
    "summaryZh": "充满活力的高对比度调色板和渐变，打造引人入胜、令人难忘的现代用户体验。",
    "swatches": [
      "#fff8d7",
      "#ffffff",
      "#1d1836",
      "#796f91"
    ],
    "isDefault": false
  },
  {
    "id": "composio",
    "label": "Composio",
    "labelZh": "Composio",
    "category": "Backend & Data",
    "summary": "Tool integration platform. Modern dark with colorful integration icons.",
    "summaryZh": "工具集成平台。现代深色风格配以彩色集成图标。",
    "swatches": [
      "#090b14",
      "#121626",
      "#f8fafc",
      "#94a3b8"
    ],
    "isDefault": false
  },
  {
    "id": "contemporary",
    "label": "Contemporary",
    "labelZh": "现代简约",
    "category": "Modern & Minimal",
    "summary": "Current-era minimalist design with bento grids, dark mode support, and high-performance accessible layouts.",
    "summaryZh": "当代极简设计，包含网格布局、深色模式和高性能无障碍布局。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "corporate",
    "label": "Corporate",
    "labelZh": "企业风格",
    "category": "Professional & Corporate",
    "summary": "Professional, brand-aligned design with structured grids, minimalist layouts, and consistent enterprise patterns.",
    "summaryZh": "专业的品牌化设计，采用结构化网格、简约布局和一致的企业级设计模式。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "cosmic",
    "label": "Cosmic",
    "labelZh": "Cosmic",
    "category": "Creative & Artistic",
    "summary": "Futuristic sci-fi aesthetic with dark themes, vibrant neon accents, and immersive spatial elements.",
    "summaryZh": "未来主义科幻美学，深色主题搭配鲜艳霓虹装饰和沉浸式空间元素。",
    "swatches": [
      "#070711",
      "#111126",
      "#f8f7ff",
      "#9d8ad4"
    ],
    "isDefault": false
  },
  {
    "id": "creative",
    "label": "Creative",
    "labelZh": "创意",
    "category": "Creative & Artistic",
    "summary": "Playful, character-driven design with expressive typography and bold graphics for landing pages and creative projects.",
    "summaryZh": "富有趣味和个性的设计风格，采用表现力强的排版和大胆的图形，适用于落地页和创意项目。",
    "swatches": [
      "#fff8d7",
      "#ffffff",
      "#1d1836",
      "#796f91"
    ],
    "isDefault": false
  },
  {
    "id": "cursor",
    "label": "Cursor",
    "labelZh": "Cursor",
    "category": "Developer Tools",
    "summary": "AI-first code editor. Sleek dark interface, gradient accents.",
    "summaryZh": "AI 优先的代码编辑器。简洁的深色界面，渐变色点缀。",
    "swatches": [
      "#f2f1ed",
      "#e6e5e0",
      "#26251e",
      "#f54e00"
    ],
    "isDefault": false
  },
  {
    "id": "dashboard",
    "label": "Dashboard",
    "labelZh": "仪表盘",
    "category": "Professional & Corporate",
    "summary": "Dark-themed cloud-platform aesthetic with modular grids, glass-like panels, and strong data hierarchy for productivity dashboards.",
    "summaryZh": "深色云平台美学风格，配备模块化网格、玻璃质感面板和强数据层级，适用于生产力仪表盘。",
    "swatches": [
      "#f4f7fb",
      "#ffffff",
      "#111827",
      "#64748b"
    ],
    "isDefault": false
  },
  {
    "id": "discord",
    "label": "Discord",
    "labelZh": "Discord",
    "category": "Productivity & SaaS",
    "summary": "Voice / chat platform. Deep blurple, dark-first surfaces, playful accent moments.",
    "summaryZh": "语音/聊天平台。深蓝紫色、深色优先界面、俏皮的强调点缀。",
    "swatches": [
      "#313338",
      "#2b2d31",
      "#dbdee1",
      "#949ba4"
    ],
    "isDefault": false
  },
  {
    "id": "dithered",
    "label": "Dithered",
    "labelZh": "抖动",
    "category": "Retro & Nostalgic",
    "summary": "Dot-pattern rendering technique that simulates shades with a limited palette for nostalgic, retro, high-contrast visuals.",
    "summaryZh": "使用点阵图案渲染技术，在有限色板下模拟明暗层次，呈现怀旧复古的高对比度视觉效果。",
    "swatches": [
      "#fff4cf",
      "#fffaf0",
      "#2a1810",
      "#8a6652"
    ],
    "isDefault": false
  },
  {
    "id": "doodle",
    "label": "Doodle",
    "labelZh": "涂鸦",
    "category": "Creative & Artistic",
    "summary": "Hand-drawn, sketch-like style with doodles, handwritten fonts, and imperfect lines for a playful, informal feel.",
    "summaryZh": "手绘素描风格，包含涂鸦元素、手写字体和不规则线条，营造轻松随意的氛围。",
    "swatches": [
      "#fff8d7",
      "#ffffff",
      "#1d1836",
      "#796f91"
    ],
    "isDefault": false
  },
  {
    "id": "dramatic",
    "label": "Dramatic",
    "labelZh": "戏剧化",
    "category": "Bold & Expressive",
    "summary": "High-contrast, theatrical design with bold layouts, immersive visuals, and unconventional compositions that command attention.",
    "summaryZh": "高对比度的戏剧性设计，采用醒目的布局、沉浸式视觉效果和非常规构图，强势吸引注意力。",
    "swatches": [
      "#090b12",
      "#121722",
      "#f8fafc",
      "#94a3b8"
    ],
    "isDefault": false
  },
  {
    "id": "duolingo",
    "label": "Duolingo",
    "labelZh": "Duolingo",
    "category": "Productivity & SaaS",
    "summary": "Language-learning platform. Bright owl green, chunky shadows, gamified joy.",
    "summaryZh": "语言学习平台。明亮的猫头鹰绿、厚重阴影、游戏化趣味。",
    "swatches": [
      "#ffffff",
      "#f7f7f7",
      "#3c3c3c",
      "#777777"
    ],
    "isDefault": false
  },
  {
    "id": "editorial",
    "label": "Editorial",
    "labelZh": "编辑部",
    "category": "Creative & Artistic",
    "summary": "Magazine-inspired editorial layout with refined serif typography, structured grids, and elegant reading experiences.",
    "summaryZh": "杂志风格的编辑排版，采用精致的衬线字体、结构化网格系统和优雅的阅读体验。",
    "swatches": [
      "#fbf7f0",
      "#fffdf8",
      "#1f1a16",
      "#7d7168"
    ],
    "isDefault": false
  },
  {
    "id": "elegant",
    "label": "Elegant",
    "labelZh": "优雅",
    "category": "Professional & Corporate",
    "summary": "Graceful, refined aesthetic with delicate typography, minimal palettes, and polished layouts that exude sophistication.",
    "summaryZh": "精致优雅的美学风格，配有精美的排版、简约的色彩方案和精良的布局，展现高雅气质。",
    "swatches": [
      "#fbf6ee",
      "#fffdf8",
      "#201914",
      "#7a6d63"
    ],
    "isDefault": false
  },
  {
    "id": "elevenlabs",
    "label": "ElevenLabs",
    "labelZh": "ElevenLabs",
    "category": "AI & LLM",
    "summary": "AI voice platform. Dark cinematic UI, audio-waveform aesthetics.",
    "summaryZh": "AI 语音平台。深色电影风 UI，音频波形美学。",
    "swatches": [
      "#ffffff",
      "#f5f5f5",
      "#000000",
      "#777169"
    ],
    "isDefault": false
  },
  {
    "id": "energetic",
    "label": "Energetic",
    "labelZh": "活力",
    "category": "Bold & Expressive",
    "summary": "Dynamic, vibrant style with thick borders, geometric shapes, high-contrast colors, and expressive typography conveying motion and vitality.",
    "summaryZh": "动感鲜明的风格，采用粗边框、几何图形、高对比度色彩和富有表现力的排版，传达运动感和生命力。",
    "swatches": [
      "#fff8d7",
      "#ffffff",
      "#1d1836",
      "#796f91"
    ],
    "isDefault": false
  },
  {
    "id": "enterprise",
    "label": "Enterprise",
    "labelZh": "Enterprise",
    "category": "Professional & Corporate",
    "summary": "Clean, high-contrast enterprise design for data-driven workflows with intuitive drag-and-drop patterns and structured layouts.",
    "summaryZh": "简洁、高对比度的企业级设计，适用于数据驱动的工作流，提供直观的拖放模式和结构化布局。",
    "swatches": [
      "#f8fafc",
      "#ffffff",
      "#0f172a",
      "#64748b"
    ],
    "isDefault": false
  },
  {
    "id": "expo",
    "label": "Expo",
    "labelZh": "Expo",
    "category": "Developer Tools",
    "summary": "React Native platform. Dark theme, tight letter-spacing, code-centric.",
    "summaryZh": "React Native 平台。深色主题，紧凑字间距，代码风格。",
    "swatches": [
      "#ffffff",
      "#f6f7f9",
      "#0b0d12",
      "#6b7280"
    ],
    "isDefault": false
  },
  {
    "id": "expressive",
    "label": "Expressive",
    "labelZh": "表现力",
    "category": "Bold & Expressive",
    "summary": "Vibrant, personality-driven design with bold colors, playful graphics, and dynamic layouts that balance creativity with structure.",
    "summaryZh": "充满活力、彰显个性的设计，采用大胆的色彩、趣味性图形和动态布局，在创意与结构之间达到平衡。",
    "swatches": [
      "#fbf8ff",
      "#ffffff",
      "#1f1730",
      "#776b88"
    ],
    "isDefault": false
  },
  {
    "id": "fantasy",
    "label": "Fantasy",
    "labelZh": "奇幻",
    "category": "Creative & Artistic",
    "summary": "Game-inspired fantasy aesthetic with bold, premium visuals, rich color palettes, and immersive thematic elements.",
    "summaryZh": "游戏风格的奇幻美学，采用大胆的高级视觉效果、丰富的色彩搭配和沉浸式主题元素。",
    "swatches": [
      "#070711",
      "#111126",
      "#f8f7ff",
      "#9d8ad4"
    ],
    "isDefault": false
  },
  {
    "id": "ferrari",
    "label": "Ferrari",
    "labelZh": "Ferrari",
    "category": "Automotive",
    "summary": "Luxury automotive. Chiaroscuro editorial, Ferrari Red accents, cinematic black.",
    "summaryZh": "豪华汽车风格。明暗对比编辑风格，Ferrari 红色点缀，电影感黑色。",
    "swatches": [
      "#0b0b0b",
      "#171717",
      "#fffaf0",
      "#a89f91"
    ],
    "isDefault": false
  },
  {
    "id": "figma",
    "label": "Figma",
    "labelZh": "Figma",
    "category": "Design & Creative",
    "summary": "Collaborative design tool. Vibrant multi-color, playful yet professional.",
    "summaryZh": "协作设计工具。鲜艳多彩，兼具趣味性与专业性。",
    "swatches": [
      "#ffffff",
      "#000000",
      "#16a34a",
      "#eab308"
    ],
    "isDefault": false
  },
  {
    "id": "flat",
    "label": "Flat",
    "labelZh": "扁平",
    "category": "Modern & Minimal",
    "summary": "Two-dimensional minimalist style with vibrant colors, clean typography, and no 3D effects for fast, user-friendly interfaces.",
    "summaryZh": "二维极简风格，采用鲜艳色彩、简洁字体，无3D效果，打造快速且用户友好的界面。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "framer",
    "label": "Framer",
    "labelZh": "Framer",
    "category": "Design & Creative",
    "summary": "Website builder. Bold black and blue, motion-first, design-forward.",
    "summaryZh": "网站构建工具。大胆的黑色和蓝色，动效优先，设计前沿。",
    "swatches": [
      "#000000",
      "#090909",
      "#ffffff",
      "#0099ff"
    ],
    "isDefault": false
  },
  {
    "id": "friendly",
    "label": "Friendly",
    "labelZh": "友好",
    "category": "Creative & Artistic",
    "summary": "Approachable, intuitive design with rounded elements, ample whitespace, and soft pastel color palettes.",
    "summaryZh": "亲和直观的设计，采用圆角元素、充足留白和柔和的粉彩配色。",
    "swatches": [
      "#fff8d7",
      "#ffffff",
      "#1d1836",
      "#796f91"
    ],
    "isDefault": false
  },
  {
    "id": "futuristic",
    "label": "Futuristic",
    "labelZh": "未来主义",
    "category": "Themed & Unique",
    "summary": "Forward-looking design with tech-inspired typography, modern layouts, and a sleek, innovation-driven aesthetic.",
    "summaryZh": "前瞻性设计，融合科技感字体、现代布局和流畅创新美学。",
    "swatches": [
      "#090b12",
      "#121722",
      "#f8fafc",
      "#94a3b8"
    ],
    "isDefault": false
  },
  {
    "id": "github",
    "label": "GitHub",
    "labelZh": "GitHub",
    "category": "Developer Tools",
    "summary": "Code-forward platform. Functional density, blue-on-white precision, Primer foundations.",
    "summaryZh": "代码优先平台。功能密度高，蓝白配色精准，基于 Primer 设计体系。",
    "swatches": [
      "#ffffff",
      "#f6f8fa",
      "#1f2328",
      "#656d76"
    ],
    "isDefault": false
  },
  {
    "id": "glassmorphism",
    "label": "Glassmorphism",
    "labelZh": "玻璃拟态",
    "category": "Morphism & Effects",
    "summary": "Frosted glass effect with translucent layers, subtle blur, and luminous borders for depth and modern elegance.",
    "summaryZh": "磨砂玻璃效果，具有半透明图层、柔和模糊和发光边框，呈现深度感和现代优雅风格。",
    "swatches": [
      "#eef6ff",
      "#102033",
      "#60708a",
      "#4f8cff"
    ],
    "isDefault": false
  },
  {
    "id": "gradient",
    "label": "Gradient",
    "labelZh": "渐变",
    "category": "Morphism & Effects",
    "summary": "Smooth color transitions and gradient-rich surfaces for modern, playful interfaces with visual depth.",
    "summaryZh": "平滑的色彩过渡和丰富的渐变效果，为现代界面增添趣味性和视觉层次。",
    "swatches": [
      "#f7f3ff",
      "#ffffff",
      "#191225",
      "#746985"
    ],
    "isDefault": false
  },
  {
    "id": "hashicorp",
    "label": "HashiCorp",
    "labelZh": "HashiCorp",
    "category": "Backend & Data",
    "summary": "Infrastructure automation. Enterprise-clean, black and white.",
    "summaryZh": "基础设施自动化。企业级简洁黑白设计。",
    "swatches": [
      "#15181e",
      "#0d0e12",
      "#efeff1",
      "#b2b6bd"
    ],
    "isDefault": false
  },
  {
    "id": "hud",
    "label": "HUD Design System",
    "category": "Themed & Unique",
    "summary": "Fighter jet / helicopter head-up display. Phosphor green on near-black, all-caps data overlays, angular geometry. Zero ambiguity at speed and altitude.",
    "swatches": [
      "#090b12",
      "#121722",
      "#f8fafc",
      "#94a3b8"
    ],
    "isDefault": false
  },
  {
    "id": "huggingface",
    "label": "Hugging Face",
    "labelZh": "Hugging Face",
    "category": "AI & LLM",
    "summary": "ML community hub. Sunny yellow accent, monospace identity, cheerful and dense.",
    "summaryZh": "机器学习社区中心。明亮的黄色主题，等宽字体风格，活泼紧凑。",
    "swatches": [
      "#fafafa",
      "#ffffff",
      "#0d1117",
      "#6b7280"
    ],
    "isDefault": false
  },
  {
    "id": "ibm",
    "label": "IBM",
    "labelZh": "IBM",
    "category": "Media & Consumer",
    "summary": "Enterprise technology. Carbon design system, structured blue palette.",
    "summaryZh": "企业级技术。Carbon 设计系统，结构化蓝色调色板。",
    "swatches": [
      "#ffffff",
      "#f4f4f4",
      "#161616",
      "#6f6f6f"
    ],
    "isDefault": false
  },
  {
    "id": "intercom",
    "label": "Intercom",
    "labelZh": "Intercom",
    "category": "Productivity & SaaS",
    "summary": "Customer messaging. Friendly blue palette, conversational UI patterns.",
    "summaryZh": "客户消息传递。友好的蓝色调色板，对话式 UI 模式。",
    "swatches": [
      "#faf9f6",
      "#ffffff",
      "#111111",
      "#7b7b78"
    ],
    "isDefault": false
  },
  {
    "id": "kami",
    "label": "kami (紙 / 纸)",
    "labelZh": "kami (紙 / 纸)",
    "category": "Editorial & Print",
    "summary": "Editorial paper system: warm parchment canvas, ink-blue accent, serif-led hierarchy. Built for resumes, one-pagers, white papers, portfolios, slide decks — anyt",
    "summaryZh": "编辑纸张系统：温暖羊皮纸画布、墨蓝色强调、衬线主导层次。适用于简历、单页文档、白皮书、作品集、幻灯片等需要高品质印刷质感的内容。支持多语言。",
    "swatches": [
      "#f5f4ed",
      "#faf9f5",
      "#141413",
      "#504e49"
    ],
    "isDefault": false
  },
  {
    "id": "kraken",
    "label": "Kraken",
    "labelZh": "Kraken",
    "category": "Fintech & Crypto",
    "summary": "Crypto trading. Purple-accented dark UI, data-dense dashboards.",
    "summaryZh": "加密货币交易。紫色点缀的深色 UI，数据密集型仪表板。",
    "swatches": [
      "#0b1020",
      "#121a33",
      "#f8fafc",
      "#8b95aa"
    ],
    "isDefault": false
  },
  {
    "id": "lamborghini",
    "label": "Lamborghini",
    "labelZh": "Lamborghini",
    "category": "Automotive",
    "summary": "Supercar brand. True black surfaces, gold accents, dramatic uppercase typography.",
    "summaryZh": "超级跑车品牌。纯黑表面、金色点缀、戏剧化大写字体。",
    "swatches": [
      "#050505",
      "#141414",
      "#f8f4e6",
      "#9b927d"
    ],
    "isDefault": false
  },
  {
    "id": "levels",
    "label": "Levels",
    "labelZh": "Levels",
    "category": "Layout & Structure",
    "summary": "Conversion-focused design that removes friction and guides users toward action through clarity, trust, and speed.",
    "summaryZh": "以转化为核心的设计，通过清晰度、信任感和速度消除摩擦，引导用户采取行动。",
    "swatches": [
      "#fbf7ef",
      "#ffffff",
      "#1f2a24",
      "#788276"
    ],
    "isDefault": false
  },
  {
    "id": "linear-app",
    "label": "Linear",
    "labelZh": "Linear",
    "category": "Productivity & SaaS",
    "summary": "Project management. Ultra-minimal, precise, purple accent.",
    "summaryZh": "项目管理。极简风格，精准设计，紫色强调。",
    "swatches": [
      "#08090a",
      "#191a1b",
      "#f7f8f8",
      "#8a8f98"
    ],
    "isDefault": false
  },
  {
    "id": "lingo",
    "label": "Lingo",
    "labelZh": "Lingo",
    "category": "Creative & Artistic",
    "summary": "Playful, minimal design with bright colors, rounded shapes, tactile 3D borders, and friendly illustrations for approachable interfaces.",
    "summaryZh": "俏皮简约的设计风格，采用明亮色彩、圆润形状、触感立体边框和友好插图，打造平易近人的界面。",
    "swatches": [
      "#fbf9ff",
      "#ffffff",
      "#1d1b2a",
      "#786f8f"
    ],
    "isDefault": false
  },
  {
    "id": "loom",
    "label": "Loom Design System",
    "category": "Themed & Unique",
    "summary": "Loom async video. Purple primary, friendly surfaces, video-first layout. Clean and professional without being corporate.",
    "swatches": [
      "#ffffff",
      "#f7f7f8",
      "#1f1f23",
      "#6b6d76"
    ],
    "isDefault": false
  },
  {
    "id": "lovable",
    "label": "Lovable",
    "labelZh": "Lovable",
    "category": "Developer Tools",
    "summary": "AI full-stack builder. Playful gradients, friendly dev aesthetic.",
    "summaryZh": "AI 全栈构建工具。俏皮渐变，友好的开发者美学。",
    "swatches": [
      "#f7f4ed",
      "#1c1c1c",
      "#5f5f5d",
      "#eceae4"
    ],
    "isDefault": false
  },
  {
    "id": "luxury",
    "label": "Luxury",
    "labelZh": "奢华",
    "category": "Professional & Corporate",
    "summary": "High-end dark aesthetic with bold headings, monochromatic palette, and premium feel for luxury brand experiences.",
    "summaryZh": "高端深色美学，配以粗体标题、单色调色板和高级质感，专为奢侈品牌体验打造。",
    "swatches": [
      "#080706",
      "#151310",
      "#fff8ea",
      "#9f927c"
    ],
    "isDefault": false
  },
  {
    "id": "mastercard",
    "label": "Mastercard",
    "labelZh": "Mastercard",
    "category": "Fintech & Crypto",
    "summary": "Global payments network. Warm cream canvas, orbital pill shapes, editorial warmth.",
    "summaryZh": "全球支付网络。温暖的奶油画布，轨道药丸形状，编辑般的温暖感。",
    "swatches": [
      "#f3f0ee",
      "#fcfbfa",
      "#141413",
      "#696969"
    ],
    "isDefault": false
  },
  {
    "id": "material",
    "label": "Material",
    "labelZh": "Material",
    "category": "Professional & Corporate",
    "summary": "Google's Material Design with layered surfaces, dynamic theming, built-in motion, and responsive cross-platform patterns.",
    "summaryZh": "Google 的 Material Design，包含分层界面、动态主题、内置动效和响应式跨平台设计模式。",
    "swatches": [
      "#f8fafd",
      "#ffffff",
      "#202124",
      "#5f6368"
    ],
    "isDefault": false
  },
  {
    "id": "meta",
    "label": "Meta (Store)",
    "labelZh": "Meta（商店）",
    "category": "E-Commerce & Retail",
    "summary": "Tech retail store. Photography-first, binary light/dark surfaces, Meta Blue CTAs.",
    "summaryZh": "科技零售商店。以摄影为主，二元明暗界面，Meta 蓝色 CTA 按钮。",
    "swatches": [
      "#ffffff",
      "#f7f8fa",
      "#1c2b33",
      "#65676b"
    ],
    "isDefault": false
  },
  {
    "id": "minimal",
    "label": "Minimal",
    "labelZh": "极简",
    "category": "Modern & Minimal",
    "summary": "Stripped-back design emphasizing whitespace, clean typography, and restrained color for maximum clarity and focus.",
    "summaryZh": "简约设计，强调留白、清晰排版和克制的色彩，实现最大化的清晰度和专注度。",
    "swatches": [
      "#ffffff",
      "#fafafa",
      "#111111",
      "#777777"
    ],
    "isDefault": false
  },
  {
    "id": "minimax",
    "label": "MiniMax",
    "labelZh": "MiniMax",
    "category": "AI & LLM",
    "summary": "AI model provider. Bold dark interface with neon accents.",
    "summaryZh": "AI 模型提供商。深色粗体界面，搭配霓虹色点缀。",
    "swatches": [
      "#ffffff",
      "#fafafa",
      "#222222",
      "#45515e"
    ],
    "isDefault": false
  },
  {
    "id": "mintlify",
    "label": "Mintlify",
    "labelZh": "Mintlify",
    "category": "Productivity & SaaS",
    "summary": "Documentation platform. Clean, green-accented, reading-optimized.",
    "summaryZh": "文档平台。简洁、绿色调、阅读优化。",
    "swatches": [
      "#ffffff",
      "#0d0d0d",
      "#666666",
      "#18e299"
    ],
    "isDefault": false
  },
  {
    "id": "miro",
    "label": "Miro",
    "labelZh": "Miro",
    "category": "Design & Creative",
    "summary": "Visual collaboration. Bright yellow accent, infinite canvas aesthetic.",
    "summaryZh": "视觉协作工具。采用明亮的黄色强调色，无限画布美学。",
    "swatches": [
      "#fff7c2",
      "#ffffff",
      "#050038",
      "#605a8a"
    ],
    "isDefault": false
  },
  {
    "id": "mission-control",
    "label": "Mission Control Design System",
    "labelZh": "Mission Control 设计系统",
    "category": "Developer Tools",
    "summary": "Space/aerospace mission monitoring. Dark command center, amber telemetry, monospace precision. Functional clarity above all else.",
    "summaryZh": "太空/航空任务监控。深色指挥中心，琥珀色遥测数据，等宽字体精度。功能清晰至上。",
    "swatches": [
      "#090b12",
      "#121722",
      "#f8fafc",
      "#94a3b8"
    ],
    "isDefault": false
  },
  {
    "id": "mistral-ai",
    "label": "Mistral AI",
    "labelZh": "Mistral AI",
    "category": "AI & LLM",
    "summary": "Open-weight LLM provider. French-engineered minimalism, purple-toned.",
    "summaryZh": "开源权重大语言模型提供商。法式极简设计，紫色调。",
    "swatches": [
      "#fffaeb",
      "#fff0c2",
      "#1f1f1f",
      "#3d3d3d"
    ],
    "isDefault": false
  },
  {
    "id": "modern",
    "label": "Modern",
    "labelZh": "现代",
    "category": "Modern & Minimal",
    "summary": "Contemporary editorial style with serif typography, minimal palettes, and clean layouts for polished digital products.",
    "summaryZh": "现代编辑风格，采用衬线字体、极简配色和简洁布局，适合精致的数字产品。",
    "swatches": [
      "#f7f8fc",
      "#ffffff",
      "#111827",
      "#6b7280"
    ],
    "isDefault": false
  },
  {
    "id": "mongodb",
    "label": "MongoDB",
    "labelZh": "MongoDB",
    "category": "Backend & Data",
    "summary": "Document database. Green leaf branding, developer documentation focus.",
    "summaryZh": "文档数据库。绿叶品牌标识，专注于开发者文档。",
    "swatches": [
      "#001e2b",
      "#1c2d38",
      "#ffffff",
      "#b8c4c2"
    ],
    "isDefault": false
  },
  {
    "id": "mono",
    "label": "Mono",
    "labelZh": "Mono",
    "category": "Modern & Minimal",
    "summary": "Monospace-driven, matrix-inspired design with high-contrast elements, compact density, and a hacker-chic aesthetic.",
    "summaryZh": "黑客风格的等宽字体驱动设计，采用矩阵风格的高对比度元素和紧凑布局。",
    "swatches": [
      "#ffffff",
      "#f7f7f7",
      "#111111",
      "#707070"
    ],
    "isDefault": false
  },
  {
    "id": "neobrutalism",
    "label": "Neobrutalism",
    "labelZh": "新野兽派",
    "category": "Bold & Expressive",
    "summary": "Modern take on brutalism with bold borders, vivid accent colors, and raw, high-contrast layouts on warm surfaces.",
    "summaryZh": "现代野兽主义风格，采用粗边框、鲜艳强调色和高对比度布局，搭配温暖的背景表面。",
    "swatches": [
      "#fff4cf",
      "#fffaf0",
      "#2a1810",
      "#8a6652"
    ],
    "isDefault": false
  },
  {
    "id": "neon",
    "label": "Neon",
    "labelZh": "霓虹",
    "category": "Morphism & Effects",
    "summary": "Electric neon glow effects with high-contrast color pairings for bold, attention-grabbing interfaces.",
    "summaryZh": "电子霓虹发光效果，配以高对比度色彩组合，打造醒目夺目的界面。",
    "swatches": [
      "#070711",
      "#111126",
      "#f8f7ff",
      "#9d8ad4"
    ],
    "isDefault": false
  },
  {
    "id": "neumorphism",
    "label": "Neumorphism",
    "labelZh": "新拟态",
    "category": "Morphism & Effects",
    "summary": "Soft, extruded UI elements with inner and outer shadows on monochromatic surfaces for a tactile, embedded look.",
    "summaryZh": "柔和、凸起的UI元素，在单色表面上带有内外阴影，呈现触感丰富的嵌入式外观。",
    "swatches": [
      "#f7eee6",
      "#fff8f1",
      "#2b211c",
      "#8a7a70"
    ],
    "isDefault": false
  },
  {
    "id": "nike",
    "label": "Nike",
    "labelZh": "Nike",
    "category": "E-Commerce & Retail",
    "summary": "Athletic retail. Monochrome UI, massive uppercase type, full-bleed photography.",
    "summaryZh": "运动零售风格。单色 UI、大号大写字体、全出血摄影。",
    "swatches": [
      "#ffffff",
      "#f5f5f5",
      "#111111",
      "#707072"
    ],
    "isDefault": false
  },
  {
    "id": "notion",
    "label": "Notion",
    "labelZh": "Notion",
    "category": "Productivity & SaaS",
    "summary": "All-in-one workspace. Warm minimalism, serif headings, soft surfaces.",
    "summaryZh": "多合一工作空间。温暖简约风格，衬线标题，柔和界面。",
    "swatches": [
      "#ffffff",
      "#f6f5f4",
      "#615d59",
      "#0075de"
    ],
    "isDefault": false
  },
  {
    "id": "nvidia",
    "label": "NVIDIA",
    "labelZh": "NVIDIA",
    "category": "Media & Consumer",
    "summary": "GPU computing. Green-black energy, technical power aesthetic.",
    "summaryZh": "GPU 计算。绿黑配色，技术力量美学。",
    "swatches": [
      "#000000",
      "#1a1a1a",
      "#ffffff",
      "#757575"
    ],
    "isDefault": false
  },
  {
    "id": "ollama",
    "label": "Ollama",
    "labelZh": "Ollama",
    "category": "AI & LLM",
    "summary": "Run LLMs locally. Terminal-first, monochrome simplicity.",
    "summaryZh": "本地运行大语言模型。终端优先，简约单色风格。",
    "swatches": [
      "#ffffff",
      "#fafafa",
      "#000000",
      "#737373"
    ],
    "isDefault": false
  },
  {
    "id": "openai",
    "label": "OpenAI",
    "labelZh": "OpenAI",
    "category": "AI & LLM",
    "summary": "Calm, near-monochrome system anchored in deep teal-black with generous white space and editorial typography.",
    "summaryZh": "以深青黑色为基调的简约近单色系统，配以宽松留白和编辑式排版。",
    "swatches": [
      "#ffffff",
      "#f5f5f5",
      "#0d0d0d",
      "#6e6e6e"
    ],
    "isDefault": false
  },
  {
    "id": "opencode-ai",
    "label": "OpenCode",
    "labelZh": "OpenCode",
    "category": "AI & LLM",
    "summary": "AI coding platform. Developer-centric dark theme.",
    "summaryZh": "AI 编程平台。开发者友好的深色主题。",
    "swatches": [
      "#201d1d",
      "#302c2c",
      "#fdfcfc",
      "#9a9898"
    ],
    "isDefault": false
  },
  {
    "id": "pacman",
    "label": "Pacman",
    "labelZh": "Pacman",
    "category": "Themed & Unique",
    "summary": "Retro arcade-inspired design with pixel fonts, dotted borders, playful high-contrast colors, and 8-bit game aesthetics.",
    "summaryZh": "复古街机风格设计，包含像素字体、点状边框、趣味高对比度色彩和 8 位游戏美学。",
    "swatches": [
      "#050505",
      "#101014",
      "#fff7d6",
      "#b9a85d"
    ],
    "isDefault": false
  },
  {
    "id": "paper",
    "label": "Paper",
    "labelZh": "纸张",
    "category": "Retro & Nostalgic",
    "summary": "Paper-textured, print-inspired design with minimal colors, clean serif/sans typography, and tactile surface qualities.",
    "summaryZh": "纸质纹理、印刷风格设计，配以极简色彩、简洁的衬线/无衬线字体以及触感表面质感。",
    "swatches": [
      "#faf3df",
      "#fffaf0",
      "#211b12",
      "#7c7160"
    ],
    "isDefault": false
  },
  {
    "id": "perplexity",
    "label": "Perplexity AI",
    "category": "AI & LLM",
    "summary": "Conversational AI search engine. Deep-dark canvas, sharp typography, single violet accent, dense information hierarchy.",
    "swatches": [
      "#0f0f10",
      "#19191a",
      "#f0f0f0",
      "#9b9b9b"
    ],
    "isDefault": false
  },
  {
    "id": "perspective",
    "label": "Perspective",
    "labelZh": "透视",
    "category": "Layout & Structure",
    "summary": "Spatial depth design with isometric views, vanishing points, and layered elements that guide attention through 3D-like realism.",
    "summaryZh": "采用等距视图、消失点和分层元素的空间深度设计，通过 3D 般的真实感引导视觉注意力。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "pinterest",
    "label": "Pinterest",
    "labelZh": "Pinterest",
    "category": "Media & Consumer",
    "summary": "Visual discovery. Red accent, masonry grid, image-first.",
    "summaryZh": "视觉发现。红色主色调，瀑布流网格，图片优先。",
    "swatches": [
      "#ffffff",
      "#f6f6f3",
      "#211922",
      "#62625b"
    ],
    "isDefault": false
  },
  {
    "id": "playstation",
    "label": "PlayStation",
    "labelZh": "PlayStation",
    "category": "Media & Consumer",
    "summary": "Gaming console retail. Three-surface channel layout, quiet-authority display type, cyan hover-scale.",
    "summaryZh": "游戏主机零售。三面通道布局，沉稳权威显示类型，青色悬停缩放。",
    "swatches": [
      "#000000",
      "#ffffff",
      "#cccccc",
      "#0070cc"
    ],
    "isDefault": false
  },
  {
    "id": "posthog",
    "label": "PostHog",
    "labelZh": "PostHog",
    "category": "Backend & Data",
    "summary": "Product analytics. Playful hedgehog branding, developer-friendly dark UI.",
    "summaryZh": "产品分析工具。俏皮的刺猬品牌形象，开发者友好的深色 UI。",
    "swatches": [
      "#fdfdf8",
      "#eeefe9",
      "#4d4f46",
      "#65675e"
    ],
    "isDefault": false
  },
  {
    "id": "premium",
    "label": "Premium",
    "labelZh": "Premium",
    "category": "Professional & Corporate",
    "summary": "Apple-inspired premium aesthetic with precise spacing, modern typography, and a refined, polished visual language.",
    "summaryZh": "Apple 风格的高端美学设计，精确的间距、现代化的排版以及精致优雅的视觉语言。",
    "swatches": [
      "#faf8f4",
      "#ffffff",
      "#1c1b19",
      "#746d63"
    ],
    "isDefault": false
  },
  {
    "id": "professional",
    "label": "Professional",
    "labelZh": "专业版",
    "category": "Professional & Corporate",
    "summary": "Polished, business-ready design with modern typography, structured layouts, and a trustworthy visual identity.",
    "summaryZh": "精致的商务设计，具备现代化排版、结构化布局和值得信赖的视觉形象。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "publication",
    "label": "Publication",
    "labelZh": "出版物",
    "category": "Creative & Artistic",
    "summary": "Print-inspired visual language for books, magazines, and reports with editorial grids and expressive typography.",
    "summaryZh": "适用于书籍、杂志和报告的印刷风格视觉语言，具有编辑网格和富有表现力的排版。",
    "swatches": [
      "#ffffff",
      "#f6f6f6",
      "#0b0b0b",
      "#666666"
    ],
    "isDefault": false
  },
  {
    "id": "raycast",
    "label": "Raycast",
    "labelZh": "Raycast",
    "category": "Developer Tools",
    "summary": "Productivity launcher. Sleek dark chrome, vibrant gradient accents.",
    "summaryZh": "效率启动器。深色优雅界面，鲜艳渐变点缀。",
    "swatches": [
      "#07080a",
      "#101111",
      "#f9f9f9",
      "#9c9c9d"
    ],
    "isDefault": false
  },
  {
    "id": "refined",
    "label": "Refined",
    "labelZh": "精致",
    "category": "Modern & Minimal",
    "summary": "Carefully curated, modern minimal style with elegant serif typography and understated, sophisticated palettes.",
    "summaryZh": "精心策划的现代极简风格，优雅的衬线字体与低调精致的配色方案。",
    "swatches": [
      "#fbf6ee",
      "#fffdf8",
      "#201914",
      "#7a6d63"
    ],
    "isDefault": false
  },
  {
    "id": "renault",
    "label": "Renault",
    "labelZh": "Renault",
    "category": "Automotive",
    "summary": "French automotive. Vibrant aurora gradients, NouvelR typography, bold energy.",
    "summaryZh": "法国汽车品牌。活力极光渐变、NouvelR 字体、大胆能量。",
    "swatches": [
      "#f7f4ef",
      "#ffffff",
      "#111111",
      "#6f6b63"
    ],
    "isDefault": false
  },
  {
    "id": "replicate",
    "label": "Replicate",
    "labelZh": "Replicate",
    "category": "AI & LLM",
    "summary": "Run ML models via API. Clean white canvas, code-forward.",
    "summaryZh": "通过 API 运行机器学习模型。简洁白色画布，代码优先。",
    "swatches": [
      "#ffffff",
      "#f8f8f8",
      "#202020",
      "#646464"
    ],
    "isDefault": false
  },
  {
    "id": "resend",
    "label": "Resend",
    "labelZh": "Resend",
    "category": "Productivity & SaaS",
    "summary": "Email API. Minimal dark theme, monospace accents.",
    "summaryZh": "电子邮件 API。极简深色主题，等宽字体点缀。",
    "swatches": [
      "#000000",
      "#f0f0f0",
      "#5c5c5c",
      "#ff801f"
    ],
    "isDefault": false
  },
  {
    "id": "retro",
    "label": "Retro",
    "labelZh": "复古",
    "category": "Retro & Nostalgic",
    "summary": "Throwback design with vintage-inspired typography, high-contrast retro palettes, and nostalgic visual elements.",
    "summaryZh": "怀旧设计风格，采用复古字体、高对比度怀旧配色和经典视觉元素。",
    "swatches": [
      "#fff4cf",
      "#fffaf0",
      "#2a1810",
      "#8a6652"
    ],
    "isDefault": false
  },
  {
    "id": "revolut",
    "label": "Revolut",
    "labelZh": "Revolut",
    "category": "Fintech & Crypto",
    "summary": "Digital banking. Sleek dark interface, gradient cards, fintech precision.",
    "summaryZh": "数字银行。简洁深色界面，渐变卡片，金融科技精准设计。",
    "swatches": [
      "#f7f8fb",
      "#ffffff",
      "#111827",
      "#64748b"
    ],
    "isDefault": false
  },
  {
    "id": "runwayml",
    "label": "Runway",
    "labelZh": "Runway",
    "category": "AI & LLM",
    "summary": "AI video generation. Cinematic dark UI, media-rich layout.",
    "summaryZh": "AI 视频生成。电影级深色 UI，富媒体布局。",
    "swatches": [
      "#000000",
      "#1a1a1a",
      "#ffffff",
      "#767d88"
    ],
    "isDefault": false
  },
  {
    "id": "sanity",
    "label": "Sanity",
    "labelZh": "Sanity",
    "category": "Backend & Data",
    "summary": "Headless CMS. Red accent, content-first editorial layout.",
    "summaryZh": "无头 CMS。红色强调色，内容优先的编辑布局。",
    "swatches": [
      "#f8f8f7",
      "#ffffff",
      "#171717",
      "#71717a"
    ],
    "isDefault": false
  },
  {
    "id": "sentry",
    "label": "Sentry",
    "labelZh": "Sentry",
    "category": "Backend & Data",
    "summary": "Error monitoring. Dark dashboard, data-dense, pink-purple accent.",
    "summaryZh": "错误监控。深色仪表板，高密度数据展示，粉紫色强调。",
    "swatches": [
      "#1f1633",
      "#150f23",
      "#ffffff",
      "#9d96b3"
    ],
    "isDefault": false
  },
  {
    "id": "shadcn",
    "label": "Shadcn",
    "labelZh": "Shadcn",
    "category": "Modern & Minimal",
    "summary": "Shadcn/ui-inspired design with minimal, clean components, monochrome palette, and utility-first patterns.",
    "summaryZh": "受 Shadcn/ui 启发的设计，具有简洁的组件、单色调色板和实用优先的模式。",
    "swatches": [
      "#ffffff",
      "#111827",
      "#64748b",
      "#e5e7eb"
    ],
    "isDefault": false
  },
  {
    "id": "shopify",
    "label": "Shopify",
    "labelZh": "Shopify",
    "category": "E-Commerce & Retail",
    "summary": "E-commerce platform. Dark-first cinematic, neon green accent, ultra-light type.",
    "summaryZh": "电商平台。深色优先电影感，霓虹绿强调色，超轻字体。",
    "swatches": [
      "#000000",
      "#02090a",
      "#ffffff",
      "#a1a1aa"
    ],
    "isDefault": false
  },
  {
    "id": "simple",
    "label": "Simple",
    "labelZh": "简约",
    "category": "Modern & Minimal",
    "summary": "Straightforward, no-frills design with clean typography, neutral colors, and intuitive layouts that stay out of the way.",
    "summaryZh": "简洁直观的设计，清晰的排版、中性色彩和易用的布局，不喧宾夺主。",
    "swatches": [
      "#f5f8ff",
      "#ffffff",
      "#101828",
      "#667085"
    ],
    "isDefault": false
  },
  {
    "id": "skeumorphism",
    "label": "Skeumorphism",
    "labelZh": "拟物化设计",
    "category": "Morphism & Effects",
    "summary": "Real-world mimicry with textured surfaces, 3D effects, and familiar physical metaphors for intuitive digital interfaces.",
    "summaryZh": "通过纹理表面、3D效果和熟悉的物理隐喻模拟真实世界，打造直观的数字界面。",
    "swatches": [
      "#f7eee6",
      "#fff8f1",
      "#2b211c",
      "#8a7a70"
    ],
    "isDefault": false
  },
  {
    "id": "slack",
    "label": "Slack",
    "category": "Productivity & SaaS",
    "summary": "Workplace communication platform. Aubergine-primary, multi-accent logo palette, light surfaces with dark sidebar, warm and approachable.",
    "swatches": [
      "#ffffff",
      "#f8f8f8",
      "#1d1c1d",
      "#616061"
    ],
    "isDefault": false
  },
  {
    "id": "sleek",
    "label": "Sleek",
    "labelZh": "简约",
    "category": "Modern & Minimal",
    "summary": "Modern minimalist aesthetic with clean lines, intentional color palette, subtle interactions, and consistent spacing.",
    "summaryZh": "现代简约美学，线条简洁，配色精心，交互细腻，间距统一。",
    "swatches": [
      "#090b12",
      "#121722",
      "#f8fafc",
      "#94a3b8"
    ],
    "isDefault": false
  },
  {
    "id": "spacex",
    "label": "SpaceX",
    "labelZh": "SpaceX",
    "category": "Media & Consumer",
    "summary": "Space technology. Stark black and white, full-bleed imagery, futuristic.",
    "summaryZh": "太空科技。鲜明的黑白配色，全出血图像，未来主义风格。",
    "swatches": [
      "#000000",
      "#f0f0fa",
      "#ffffff",
      "#d8d8e6"
    ],
    "isDefault": false
  },
  {
    "id": "vercel",
    "label": "Vercel",
    "labelZh": "Vercel",
    "category": "Developer Tools",
    "summary": "Frontend deployment. Black and white precision, Geist font.",
    "summaryZh": "前端部署。黑白精准设计，Geist 字体。",
    "swatches": [
      "#ffffff",
      "#171717",
      "#666666",
      "#0070f3"
    ],
    "isDefault": false
  },
  {
    "id": "vibrant",
    "label": "Vibrant",
    "labelZh": "Vibrant",
    "category": "Bold & Expressive",
    "summary": "Lively, colorful design with bold playful typography, warm accents, and dynamic visual energy.",
    "summaryZh": "充满活力的多彩设计，采用大胆俏皮的字体排版、温暖的强调色和动感的视觉能量。",
    "swatches": [
      "#fff8d7",
      "#ffffff",
      "#1d1836",
      "#796f91"
    ],
    "isDefault": false
  },
  {
    "id": "vintage",
    "label": "Vintage",
    "labelZh": "复古风格",
    "category": "Retro & Nostalgic",
    "summary": "1950s-1990s nostalgia with skeuomorphic touches, grainy textures, retro color palettes, and pixel-style typography.",
    "summaryZh": "1950至1990年代怀旧风格，包含拟物化设计、颗粒纹理、复古色板和像素字体。",
    "swatches": [
      "#faf3df",
      "#fffaf0",
      "#211b12",
      "#7c7160"
    ],
    "isDefault": false
  },
  {
    "id": "vodafone",
    "label": "Vodafone",
    "labelZh": "Vodafone",
    "category": "Media & Consumer",
    "summary": "Global telecom brand. Monumental uppercase display, Vodafone Red chapter bands.",
    "summaryZh": "全球电信品牌。大写纪念碑式展示字体，Vodafone Red 章节色带。",
    "swatches": [
      "#ffffff",
      "#f4f4f4",
      "#1f1f1f",
      "#6f7375"
    ],
    "isDefault": false
  },
  {
    "id": "voltagent",
    "label": "VoltAgent",
    "labelZh": "VoltAgent",
    "category": "AI & LLM",
    "summary": "AI agent framework. Void-black canvas, emerald accent, terminal-native.",
    "summaryZh": "AI 智能体框架。深黑画布，翠绿点缀，终端原生风格。",
    "swatches": [
      "#07110c",
      "#101c16",
      "#f4fff8",
      "#8ba493"
    ],
    "isDefault": false
  },
  {
    "id": "warm-editorial",
    "label": "Warm Editorial",
    "labelZh": "暖色社论",
    "category": "Starter",
    "summary": "A serif-led magazine aesthetic. Terracotta accent on warm off-white paper — good for long-form, editorial, and brand-led marketing pages.",
    "summaryZh": "衬线字体主导的杂志美学。温暖米白纸张上的陶土色点缀——适合长篇内容、社论和品牌营销页面。",
    "swatches": [
      "#fbf6ee",
      "#fffdf8",
      "#201914",
      "#7a6d63"
    ],
    "isDefault": false
  },
  {
    "id": "warp",
    "label": "Warp",
    "labelZh": "Warp",
    "category": "Developer Tools",
    "summary": "Modern terminal. Dark IDE-like interface, block-based command UI.",
    "summaryZh": "现代化终端工具。深色 IDE 风格界面，基于块的命令 UI。",
    "swatches": [
      "#161412",
      "#1f1d1b",
      "#faf9f6",
      "#868584"
    ],
    "isDefault": false
  },
  {
    "id": "webex",
    "label": "Webex",
    "category": "Productivity & SaaS",
    "summary": "Collaboration platform. Momentum typography, blue action system, multi-user accent spectrum.",
    "swatches": [
      "#f6f8fb",
      "#ffffff",
      "#0f172a",
      "#64748b"
    ],
    "isDefault": false
  },
  {
    "id": "webflow",
    "label": "Webflow",
    "labelZh": "Webflow",
    "category": "Design & Creative",
    "summary": "Visual web builder. Blue-accented, polished marketing site aesthetic.",
    "summaryZh": "可视化网页构建工具。蓝色调、精致的营销网站美学。",
    "swatches": [
      "#ffffff",
      "#080808",
      "#5a5a5a",
      "#d8d8d8"
    ],
    "isDefault": false
  },
  {
    "id": "wechat",
    "label": "WeChat Design System",
    "category": "Social & Messaging",
    "summary": "Brand visual language for WeChat Mini Programs, official accounts, and open ecosystem extensions.",
    "swatches": [
      "#ededed",
      "#f7f7f7",
      "#1a1a1a",
      "#888888"
    ],
    "isDefault": false
  },
  {
    "id": "wired",
    "label": "WIRED",
    "labelZh": "WIRED",
    "category": "Media & Consumer",
    "summary": "Tech magazine. Paper-white broadsheet density, custom serif display, mono kickers, ink-blue links.",
    "summaryZh": "科技杂志。纸白色报纸密度，定制衬线标题，等宽引题，墨蓝色链接。",
    "swatches": [
      "#ffffff",
      "#f2f2f2",
      "#000000",
      "#666666"
    ],
    "isDefault": false
  },
  {
    "id": "wise",
    "label": "Wise",
    "labelZh": "Wise",
    "category": "Fintech & Crypto",
    "summary": "Money transfer. Bright green accent, friendly and clear.",
    "summaryZh": "汇款转账。明亮的绿色强调色，友好清晰。",
    "swatches": [
      "#ffffff",
      "#e8ebe6",
      "#0e0f0c",
      "#868685"
    ],
    "isDefault": false
  },
  {
    "id": "x-ai",
    "label": "xAI",
    "labelZh": "xAI",
    "category": "AI & LLM",
    "summary": "Elon Musk's AI lab. Stark monochrome, futuristic minimalism.",
    "summaryZh": "Elon Musk 的 AI 实验室。极简黑白，未来主义风格。",
    "swatches": [
      "#1f2228",
      "#ffffff",
      "#16a34a",
      "#eab308"
    ],
    "isDefault": false
  },
  {
    "id": "xiaohongshu",
    "label": "Xiaohongshu",
    "labelZh": "Xiaohongshu",
    "category": "Media & Consumer",
    "summary": "Lifestyle UGC social platform. Singular brand red, generous radius, content-first.",
    "summaryZh": "生活方式UGC社交平台。独特的品牌红、大圆角、内容优先。",
    "swatches": [
      "#f5f5f5",
      "#ffffff",
      "#ff2442",
      "#fafafa"
    ],
    "isDefault": false
  },
  {
    "id": "zapier",
    "label": "Zapier",
    "labelZh": "Zapier",
    "category": "Productivity & SaaS",
    "summary": "Automation platform. Warm orange, friendly illustration-driven.",
    "summaryZh": "自动化平台。温暖橙色，友好的插画驱动风格。",
    "swatches": [
      "#fff7ed",
      "#ffffff",
      "#2d2a26",
      "#7c6f64"
    ],
    "isDefault": false
  }
];
